services:
  wildfly:
      image: quay.io/wildfly/wildfly
      ports:
        - "80:8080"
      volumes:
        - "./target/livraisonsMyPack-1.0-SNAPSHOT.war:/opt/jboss/wildfly/standalone/deployments/ROOT.war"
  dockerDatabase:
    image: postgres
    environment:
      - POSTGRES_PASSWORD=admin
      - POSTGRES_USER=postgres
      - POSTGRES_DB=livraison
    volumes:
      - appDatabase:/var/lib/postgresql/data
    ports:
      - 5434:5432
volumes:
  appDatabase: